### ISSUE TITLE
Wyświetlanie i modyfikacja swoich danych przez użytkownika

### ISSUE THREAD

**Issue by xEdziu** [xEdziu/Klama#21]
Z wyświetlania:

- [x] dane osobowe,
- [x] historia karnetów
- [x] historia zakupów
- [x] historia rezerwacji / wypożyczeń

Z modyfikowania:

- [ ] dane osobowe

**Comment by xEdziu** [comment]
historia zakupów za jednym zamachem ogarnąłem w #12

**Comment by xEdziu** [comment]
@ZuberRS03 tutaj też myślisz o tym, że to będzie nasz łączony task? ja przy okazji zrobiłem historię zakupów, mogę machnąć wyświetlanie swoich danych osobowych i ich modyfikacje, a tobie zostanie historia karnetów, rezerwacji i wypożyczeń

**Comment by ZuberRS03** [comment]
No dobra, na razie kminie dalej z wypożyczalnią

**Comment by ZuberRS03** [comment]
Historie karnetów i rezerwacji/wypożyczeń ogarnąłem przy okazji innych tasków.
